name: SonarCloud and Pixeebot Integration
on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  share:
    name: Upload Sonar Results to Pixeebot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: pixee/upload-tool-results-action@v2
        with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
